name: First Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev-yossi'

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "First Workflow - Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        run: npm test

  report:
    needs: test
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Output Information
        run: echo "okkkkk"
